#!/bin/bash

Script for segmentation
Originally by David Fuentes, MD Anderson Cancer Center
Edited by Jonas Actor, Rice University
25 Feb 2019

----------
PURPOSE

Construct models for liver segmentation of CT data.
The following script does the following:
	- Creates an npy database for the CT data
	- Trains a model on all of the specified dataset (kfold with k=1)
	- Trains k models using k-fold validation
	- Creates a script to test the k-fold validation models on the withheld datasets
	- Performs the k-fold testing
----------
USAGE

In your directory of choice where you will run this script, make sure the code liver2.py exists, and that the options for the data
directory is correct. Not all of the options for the liver2.py Python script are accessible via the makemodel.sh script.

If no database file has been constructed previously, run
$ ./makemodel.sh <location/of/dbfile.csv> <numepochs> <kfolds> <location/of/directory/for/output>

If a database npy file already exists, edit the script makemodel.sh to comment out the first line of code, and run the command above.


----------
NOTES

Statistical analysis can be run from the makefile script ending in -stats.makefile after the makemodel.sh script is run.
This script is created independently so that the statistical analysis of the segmentation output can be run without
occupying the same computing resources (i.e. GPUs).

Screen output from the makemodel.sh script is captured to the file nohup.out . 

When completed, the script for prediction ending in -predict.makefile is moved to the output directory.
If the output directory is not the top-level directory where the liver2.py code resides, this script will not be able
to run successfully without moving it back to the top-level directory.
